language: cpp
cache:
  directories:
    - llvm
matrix:
  include:
  - os: linux
    dist: xenial
    compiler: gcc
    env: TRIPLE="x86_64-unknown-linux-gnu"
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-9
    before_install:
    - sudo rm /usr/bin/gcc
    - sudo rm /usr/bin/g++
    - sudo ln -s /usr/bin/gcc-9 /usr/bin/gcc
    - sudo ln -s /usr/bin/g++-9 /usr/bin/g++
    - gcc --version
    - g++ --version
  - os: osx
    osx_image: xcode10.3
    compiler: clang
    env: TRIPLE="x86_64-apple-darwin16"
script:
  # if setup has not already been done, run it
  - test -f llvm/SETUP_COMPLETE || bash linux_setup.sh $TRIPLE
  # osx doesn't have timeout function, using this instead: https://gist.github.com/jaytaylor/6527607
  - function timeout() { perl -e 'alarm shift; exec @ARGV' "$@"; }
  # run the build for at most 30mins=1800s
  - timeout 1800 bash linux_continue.sh
  # if the build didn't finish in time
  #  - the above line exits with an error code
  #  - the directory `llvm` in cache is updated with the current contents
  #  - travis job can be manually restarted: will continue build using the cached files
  - cd tarball
before_deploy:
  tar -zcvf llvm-static-$TRAVIS_OS_NAME.tgz *
deploy:
  provider: releases
  api_key:
    secure: iEZlN4x/0BtFDeXKJs2eaWr2Wqlr3cbxlVF/sTM+elTzyM1TNdENTZIOTfjPe6iZcE/BeYTajs4lne5Sqlx69752KQDkvGFwg7CUCJ+6DFWS3KG3siLAFUxGbE6Om8i7DaU9q/XaLgHD9ZTivUVPo5Y7mZYdq9U6ZmZOI02m+t6jRhNYkhThS2AYnlBP58w5hMy/f+uFYd7c1WL3GNz4ouJ2dr4pobtNEuj3E4+D+mG+tBHLM5lWXQz+HgiW99wpraCEfaBrkpHk9/dPm9Q8fLaJn7RNjjzG3AoLwAEMx2TiQtaE9sGoX3iYofKp05y+duPGpcciK3EMXQGK0iYALXVvcqRxDQeSfc81CCvVgUr/h2NuHk/8GvYcjWCNBVEl9THpNMVvpxBxenK6ekPcoN7OC26dyiq0+DwsnYH48nVktngl+OS/Jbha0JU3HoIPy6rXfjZqPjjxMuxsiY3BoM1eFCXye65MOMhcPr5X6MHZfK6xOEOeiFCBTOeT2F7VmPChqohIXqNwE2oNyu1pse8OCIqg1S/XuoZV+eoKkbwhNSZvYNzAjxKfLtxZ2ZgoKRHXlRxp46ETmSEzPCp4DzPnwbwVtnlKCfUPE4ijvXcI2i2JWkottdUZajVQKtrHYwL3t5avKoKm9CJX19ofchaoBLpxGIXQq11cIiA3HvU=
  file:
    - llvm-static-$TRAVIS_OS_NAME.tgz
  skip_cleanup: true
  on:
    repo: lkeegan/llvm-static
    tags: true
    all_branches: true
notifications:
  email: false
